# docker-compose.yml
version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=news_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - .:/app  # Optional, for development

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=listen_audio_db
    ports:
      - "5436:5436"  # Optional, for local access
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: